apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: postgres-external
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector: null
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg
  namespace: postgres-external
  labels:
    app: postgres
subsets:
- addresses:
  - ip: 109.74.200.33
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
