apiVersion: v1
kind: Service
metadata:
  name: pg
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector: null
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg
  labels:
    app: postgres
subsets:
- addresses:
  - ip: 178.79.129.52
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
