apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  serviceName: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      serviceAccountName: influxdb
      containers:
      - name: influx
        image: influxdb:1.8.2
        env:
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        ports:
        - containerPort: 8086
          name: api
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: data
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: api
            scheme: HTTP
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "fast" # StorageOS storageClass
      resources:
        requests:
          storage: 20Gi
