apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector: null
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  labels:
    app: mysql
subsets:
- addresses:
  - ip: 109.237.26.91
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
